### ISSUE TITLE
Push Dashboard token signing returns different values every time

### ISSUE THREAD

**Issue by groovecoder** [jrconlin/WebPushDataTestPage#17]
When trying to sign the push dashboard token with the VAPID private key on the test page, it generates a different signed value every time, so the signed token fails validation.

**Comment by jrconlin** [comment]
Yeah, that's not a bug, but the way that Crypto.subtle and ECDSA works. Unfortunately, it means that in order to verify, you'll need the corresponding public key and the original token value. 

I've added a function to the vapid.js https://github.com/jrconlin/WebPushDataTestPage/pull/18/files#diff-99a2feb7627bdbd75bc8d36366f932c0R291 inside of #18 that shows how to verify an ECDSA signed token. Feel free to either use that or craft yours appropriately.

**Comment by groovecoder** [comment]
I'm storing the urlsafe_b64encode'd public key value that the user adds via the dashboard and I generate and store the token value as well. When the user pastes the (urlsafe_b64encode'd) signed token value, I send it thru this verification function:

https://github.com/mozilla-services/push-dev-dashboard/blob/master/push/models.py#L120

Which seems to match the `verifyString` function of `vapid.js` ? Unless, like you said - there's something different between the way python & js convert between strings and array buffers? :cry:
